apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cc.ccloud-secrets
  namespace: default
spec:
  encryptedData:
    CCLOUD_EMAIL: AgCvcCA1MWN3t3GPplZiKoAQaQwDlaZSKnENWdiHnmgsIaNdyHLXILKJqjQnAvcZna1gEKCLZWYWgH892WMwTEvkcKXyEPXwoOhpCgw3bBL3tczfcP3YjPfBgZxW6xG/A0/uv/mwTJN//w4juvlCXsMjch597K5TRwuTZHVEAsusqrTNORXOqTGHt7CwcrTpcgySKaWqdjwLzFCSpOaXynP39RRGfpm9xLcsoIiSL5nxpaNIpJa30qrKLljAEUdnpe0aeKKfHcn/NkGz8vScTt9f9R5Vgif6WVjImVpOrCEu2tpyQYwRtTCTyt9hCy/Ogdk9Ul0LMyd9L1lr3/W9svYCy+zcG4KpnMRG+yZjigTwyki+4JsETJTqmGclPggWo3NwZCmS2GuLdb7354V1l4uFu2CdDOhtKKtgOPGQrAz1SL+dh15XdpMy3U1C36SVgXiMSiJZ8nP5DvpgkUOGj/fIAKQiBN72wvtB3KdkbqPZ5tWXcbVuUYo7iuVAEfdLgwRWkGg4+GMFabt5Wuh9hijH5prrR66ChA0+Qh0xRGuJ615UWxiUBp4ZlSrlritaVXdNiXx3dA/lgtf29QVZc4dONI4uQyKNdueHwIIRdQr0Cu1Vmr49+TSuilBcqRhuyURwCJW7TVkZpTiRtcNfxpJ0adWIYRZM7YTV4cFG2///0+N1lJNrKt0N5p0DDqY85hYcdwskKm00HSDfZIglsYY1sJ0ROYAHdE8xEkRW4A==
    CCLOUD_PASSWORD: AgCceOwhM3wN0bBfL79kjmJKaA/tvn1HIZLKnwixbXqjCApXPVzPsPG69KFxyJ1pyfuRCPms4KlFmS6xJeYzuhuSRFTFr9umGKpZ9hzNHUAa3lnMVwBz98lu4FASAWDdGREDggCepP/aPq/EIguxXbhchWhz5hFZkCsX4yf9YzWsdSOmncozkUz94u4hMtyv/B2+3ncV0OFeen2dA8M7NjmMpazycm0KSgEMHrgAtcz1+In60BY9Ii6/JDXKIFH33y+LwJpBXjfOguZXJK942y+nHLRCFdFk44j4E9c92WAu3wLeUrNH7kYnGlNyK1eBQcrI37iW2NfsRSOGlzTcUSoypPRwqSqr5pKG+y5EwRAdMW2vt5NrId8pNU84/ACzxdRF41AhOoPKHKQm4hzstmtg4hW7ESsChNkKcZWTOGvGfgjh3YIcNkIJ4VCHqmafputmi5BIbD2ogzpZ8/gC9WlK2hY5j5zMjqWS3RHbuirLirgfstbdWfWQc46N/Ky55Tt2NlKyoZ2aSKR1P8BnUu//gulImc8tERgzGqpEYth+Q9gRouxdeJ+6U98N6N9jFCjh/fmTaedyHCUoyHblop9zfGjUF4183QOtAcb+Up5ntcRH7AkYhdJRLcXpIkOUGEn1/3KCPYTfl4AoAqOgR3MTqlBBAummsGq/s821U3chIuYe4B31SayzeiX/TuxRAljK9XP7Ox3OyWbi1Ntvc6aPzlmyOg==
  template:
    metadata:
      creationTimestamp: null
      name: cc.ccloud-secrets
      namespace: default

