apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-ops-ccloud-environment
  labels:
    destination: ccloud
data:
  service-accounts: |
    [
      { "name": "microservices-orders-client",
        "description": "Account for client microservices orders client apps"
      }, {
        "name": "streaming-ops-sr-client",
        "description": "Account for client access to streaming-ops environment schema registry"
      }, {
        "name": "connect-worker-client",
        "description": "Account for connect worker client access"
      }
    ]

