#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: ccloud-admin-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: configmaps-admin_ccloud-admin-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmaps-admin
subjects:
  - kind: ServiceAccount
    name: ccloud-admin-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-admin
  namespace: default
roleRef:
  kind: Role
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ccloud-admin-sa
    namespace: default
