apiVersion: v1
kind: ConfigMap
metadata:
  name: cc.shared-client-config
  namespace: default
data:
  shared-client.properties: |
    security.protocol=SASL_SSL
    ssl.endpoint.identification.algorithm=https
    sasl.mechanism=PLAIN
    basic.auth.credentials.source=USER_INFO
    replication.factor=3

