apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: monitor-configmaps
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: configmaps-admin
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","patch","update","get","watch","list"]
