apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: confluent
  name: secret-admin
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","patch","update","get","watch","list"]
