apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: confluent
commonLabels:
  variant: dev
resources:
- ../base/
patchesStrategicMerge:
- ccloud/microservices-ccloud-environment.yaml
